/**
 * Notification table for the database. Used to store notification details for events.
 * Automatically generated by sequelize.
 * DO NOT MODIFY
 */
'use strict';
const {
  Model
} = require('sequelize');
module.exports = (sequelize, DataTypes) => {
  class Notification extends Model {
    /**
     * Helper method for defining associations.
     * This method is not a part of Sequelize lifecycle.
     * The `models/index` file will call this method automatically.
     */
    static associate(models) {
      // define association here
    }
  }
  Notification.init({
    eventId: DataTypes.INTEGER,
    notification: DataTypes.TEXT
  }, {
    sequelize,
    modelName: 'Notification',
  });
  return Notification;
};