/**
 * Replies table for the database. Used to store Replies details for events.
 * Automatically generated by sequelize.
 * DO NOT MODIFY
 */
'use strict';
const {
  Model
} = require('sequelize');
module.exports = (sequelize, DataTypes) => {
  class Replie extends Model {
    /**
     * Helper method for defining associations.
     * This method is not a part of Sequelize lifecycle.
     * The `models/index` file will call this method automatically.
     */
    static associate(models) {
      // define association here
    }
  }
  Replie.init({
    reviewId: DataTypes.INTEGER,
    reply: DataTypes.TEXT,
    eventId: DataTypes.INTEGER,
    username: DataTypes.STRING,
  }, {
    sequelize,
    modelName: 'Replie',
  });
  return Replie;
};