/**
 * Review table for the database. Used to store reviews details for events.
 * Automatically generated by sequelize.
 * DO NOT MODIFY
 */
'use strict';
const {
  Model
} = require('sequelize');
module.exports = (sequelize, DataTypes) => {
  class Review extends Model {
    /**
     * Helper method for defining associations.
     * This method is not a part of Sequelize lifecycle.
     * The `models/index` file will call this method automatically.
     */
    static associate(models) {
      // define association here
    }
  }
  Review.init({
    userId: DataTypes.INTEGER,
    eventId: DataTypes.INTEGER,
    star: DataTypes.INTEGER,
    review: DataTypes.TEXT,
    username: DataTypes.STRING,
  }, {
    sequelize,
    modelName: 'Review',
    timestamps: false,
  });
  return Review;
};