/**
 * Tag table for the database. Used to store tags for events.
 * Automatically generated by sequelize.
 * DO NOT MODIFY
 */
'use strict';
const {
    Model
} = require('sequelize');
module.exports = (sequelize, DataTypes) => {
    class Tag extends Model {
    /**
     * Helper method for defining associations.
     * This method is not a part of Sequelize lifecycle.
     * The `models/index` file will call this method automatically.
     */
        static associate(models) {
            // define association here
        }
    }
    Tag.init({
        tag: DataTypes.STRING
    }, {
        sequelize,
        modelName: 'Tag',
        timestamps: false,
    });
    
    return Tag;
};