/**
 * User table for the database. Used to user details.
 * Automatically generated by sequelize.
 * DO NOT MODIFY
 */
'use strict';
const { Model } = require('sequelize');
module.exports = (sequelize, DataTypes) => {
    class User extends Model {
        /**
         * Helper method for defining associations.
         * This method is not a part of Sequelize lifecycle.
         * The `models/index` file will call this method automatically.
         */
        static associate(models) {
            // define association here
        }
    }
    User.init({
        username: DataTypes.STRING,
        password: DataTypes.STRING,
        firstName: DataTypes.STRING,
        lastName: DataTypes.STRING,
        email: DataTypes.STRING,
        gender: DataTypes.STRING,
        cardNumber: DataTypes.STRING,
        cvc: DataTypes.STRING,
        expiryDate: DataTypes.DATEONLY,
        dob: DataTypes.DATEONLY,
        biography: DataTypes.TEXT,
        token: DataTypes.STRING,
        eventTags: DataTypes.ARRAY(DataTypes.STRING),
        student: DataTypes.BOOLEAN,
        eventsJoined: DataTypes.ARRAY(DataTypes.INTEGER),
        eventsHosted: DataTypes.ARRAY(DataTypes.INTEGER),
    }, {
        sequelize,
        modelName: 'User',
        timestamps: false,
    });
    
    return User;
};